//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlDiffLib.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlDiffLib.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;catalog&gt;
        ///  &lt;book id=&quot;bk101&quot;&gt;
        ///    &lt;author&gt;Gambardella, Matthew&lt;/author&gt;
        ///    &lt;title&gt;XML Developer&apos;s Guide&lt;/title&gt;
        ///    &lt;genre&gt;Computer&lt;/genre&gt;
        ///    &lt;price&gt;44.95&lt;/price&gt;
        ///    &lt;publish_date&gt;2000-10-01&lt;/publish_date&gt;
        ///    &lt;description&gt;
        ///      An in-depth look at creating applications
        ///      with XML.
        ///    &lt;/description&gt;
        ///  &lt;/book&gt;
        ///  &lt;book id=&quot;bk102&quot;&gt;
        ///    &lt;author&gt;Ralls, Kim&lt;/author&gt;
        ///    &lt;title&gt;Midnight Rain&lt;/title&gt;
        ///    &lt;genre&gt;Fantasy&lt;/genre&gt;
        ///    &lt;price&gt;5.95&lt;/price&gt;
        ///    &lt;publish_date&gt;2000-12-16&lt;/publish_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exampleA {
            get {
                return ResourceManager.GetString("exampleA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;catalog&gt;
        ///  &lt;book id=&quot;bk101&quot;&gt;
        ///    &lt;author&gt;Gambardella, Matthew&lt;/author&gt;
        ///    &lt;title&gt;XML Developer&apos;s Guide&lt;/title&gt;
        ///    &lt;genre&gt;Computer&lt;/genre&gt;
        ///    &lt;price&gt;44.95&lt;/price&gt;
        ///    &lt;publish_date&gt;2015-10-12&lt;/publish_date&gt;
        ///    &lt;description&gt;
        ///      An in-depth look at creating applications
        ///      with XML.
        ///    &lt;/description&gt;
        ///  &lt;/book&gt;
        ///  &lt;book id=&quot;bk102&quot;&gt;
        ///    &lt;author&gt;Ralls, Kim&lt;/author&gt;
        ///    &lt;title&gt;Midnight Rain&lt;/title&gt;
        ///    &lt;genre&gt;Mystery&lt;/genre&gt;
        ///    &lt;price&gt;5.95&lt;/price&gt;
        ///    &lt;publish_date&gt;2016-02-16&lt;/publish_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exampleB {
            get {
                return ResourceManager.GetString("exampleB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModulePosting
        ///	CPKFile=&quot;&quot;
        ///	Mode=&quot;Test&quot;
        ///	TypeOfPost=&quot;Post&quot;&gt;
        ///	&lt;Company
        ///		Address1=&quot;6500 Pinecrest Dr Ste 100&quot;
        ///		Address2=&quot;&quot;
        ///		AltPhone=&quot;&quot;
        ///		AltPhoneExt=&quot;&quot;
        ///		CMPProductID=&quot;3506&quot;
        ///		City=&quot;Plano&quot;
        ///		CompanyCode=&quot;&quot;
        ///		CompanyData=&quot;&quot;
        ///		CompanyID=&quot;10032162&quot;
        ///		ContractNumber=&quot;&quot;
        ///		CountyMutual=&quot;&quot;
        ///		EMail=&quot;&quot;
        ///		Fax=&quot;&quot;
        ///		GenericFinanceAPRCharge=&quot;0&quot;
        ///		GenericFinanceAPRCharge2=&quot;0&quot;
        ///		GenericFinanceAPR_FlatChargeAmount=&quot;31&quot;
        ///		GenericFinanceAPR_FlatChargeAmount2=&quot;31&quot;
        ///		GenericFinanceAmountNotFinanced=&quot;100&quot;
        ///		GenericFinanceAmou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HAAR01000 {
            get {
                return ResourceManager.GetString("HAAR01000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ModulePosting
        ///	CPKFile=&quot;&quot;
        ///	Mode=&quot;Test&quot;
        ///	TypeOfPost=&quot;Post&quot;&gt;
        ///	&lt;Company
        ///		Address1=&quot;6500 Pinecrest Dr Ste 100&quot;
        ///		Address2=&quot;&quot;
        ///		AltPhone=&quot;&quot;
        ///		AltPhoneExt=&quot;&quot;
        ///		CMPProductID=&quot;3506&quot;
        ///		City=&quot;Plano&quot;
        ///		CompanyCode=&quot;&quot;
        ///		CompanyData=&quot;&quot;
        ///		CompanyID=&quot;10032162&quot;
        ///		ContractNumber=&quot;&quot;
        ///		CountyMutual=&quot;&quot;
        ///		EMail=&quot;&quot;
        ///		Fax=&quot;&quot;
        ///		GenericFinanceAPRCharge=&quot;0&quot;
        ///		GenericFinanceAPRCharge2=&quot;0&quot;
        ///		GenericFinanceAPR_FlatChargeAmount=&quot;31&quot;
        ///		GenericFinanceAPR_FlatChargeAmount2=&quot;31&quot;
        ///		GenericFinanceAmountNotFinanced=&quot;100&quot;
        ///		GenericFinanceAmou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HAAR01001 {
            get {
                return ResourceManager.GetString("HAAR01001", resourceCulture);
            }
        }
    }
}
